name: Polashot build, push to GCR and update docker-compose

on:
  push:
    tags:
      - "*"
  release:
    types: [released]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Auth service account
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t eu.gcr.io/polashot/${{ github.event.repository.name }}:${{ github.ref_name }} .
        docker push eu.gcr.io/polashot/${{ github.event.repository.name }}:${{ github.ref_name }}

  update-docker-compose:
    needs: build-and-push
    env:
      IMAGE_TAG: ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Modify file
        run: |
          envsubst < docker-compose.yaml > docker-compose-${{ github.event.repository.name }}.yaml

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload docker composer file to server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose-${{ github.event.repository.name }}.yaml github@${{ secrets.DEPLOY_SERVER_IP }}:/app/docker-compose-${{ github.event.repository.name }}.yaml

      - name: Restart docker-compose service
        run: |
          ssh -o StrictHostKeyChecking=no github@${{ secrets.DEPLOY_SERVER_IP }} "cd /app && sudo docker compose up --detach --no-deps ${{ github.event.repository.name }}"
